name: CI

on:
  push:
    branches: [main, develop, feature/user_authentication]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Create Google Services file
        run: cat /home/runner/work/Dora/Dora/app/google-services.json | base64

      - name: Put data in Google Services file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/Dora/Dora/app/google-services.json

      - name: Install Firebase tools
        run: npm install -g firebase-tools

      - name: Run emulators and tests
        run: firebase emulators:exec './gradlew connectedAndroidTest'

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble

      - name: Run local tests
        run: ./gradlew test

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs