name: CI

on:
  push:
    branches: [main, develop, feature/user_authentication]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Test and build
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - uses: w9jds/setup-firebase@main
        with:
          tools-version: 11.9.0
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Create Google Services file
        run: cat /home/runner/work/Dora/Dora/app/google-services.json | base64

      - name: Put data in Google Services file
        working-directory: ./app
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > google-services.json

      - name: Android emulator runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Run android tests
        run: firebase emulators:exec --only firestore,auth --project $${{ secrets.PROJECT_ID }} './gradlew connectedAndroidTest'

      - name: Run local tests
        run: ./gradlew test

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs